name: Daily Papers

permissions:
  issues: write

on:
 schedule: 
   - cron: '*/5 * * * *'

jobs:
  papers:
    runs-on: ubuntu-latest
    steps:
      - name: Generate papers
        id: paper
        run: |
          array=$(curl -H 'Content-Type: application/json' \
                       -d '{"contents":[{"parts":[{"text":"https://arxiv.org/search/cs?query=llm&searchtype=all&abstracts=show&order=-announced_date_first&size=50 请输入里面前10篇论文的 id，输出为 json 数组"}]}]}' \
                       -X POST "https://palm-proxy2-kappa.vercel.app/v1beta/models/gemini-pro:generateContent?key=${{ secrets.GEMINI_TOKEN }}" \
                       | jq -r '.candidates[0].content.parts[0].text' \
                       | sed -e '1d;$d')
          title=`date "+%Y-%m-%d"`
          echo "IDS=$array" >> "$GITHUB_OUTPUT"
          echo "TITLE=$title" >> "$GITHUB_OUTPUT"
      - name: create an issue
        uses: dacbd/create-issue-action@main
        with:
          token: ${{ github.token }}
          title: Papers ${{ steps.paper.outputs.TITLE }}
          body: |
            - 1
            - 2
          
