name: Daily Papers

on:
 schedule: 
   - cron: '*/5 * * * *'

jobs:
  papers:
    runs-on: ubuntu-latest
    steps:
      - name: Generate papers
        id: paper
        run: |
          array=$(curl -H 'Content-Type: application/json' \
                       -d '{"contents":[{"parts":[{"text":"https://arxiv.org/search/cs?query=llm&searchtype=all&abstracts=show&order=-announced_date_first&size=50 请输入里面前10篇论文的 id，输出为 json 数组"}]}]}' \
                       -X POST "https://palm-proxy2-kappa.vercel.app/v1beta/models/gemini-pro:generateContent?key=${{ secrets.GEMINI_TOKEN }}" \
                       | jq -r '.candidates[0].content.parts[0].text' \
                       | sed -e '1d;$d')
          echo $array
          echo "IDS=$array"
      - uses: nashmaniac/create-issue-action@v1.2
        name: Create Issue Action
        with:
          title: 'Daily Paper ${`date "+%Y-%m-%d"`}'
          token: ${{secrets.GITHUB_TOKEN}}
          assignees: ${{github.actor}}
          body: |
            | test | test |
            | --- | --- |
            | test | test |
