name: Daily Papers

on:
 schedule: 
   - cron: '*/5 * * * *'
 issues:
    types:
      - opened

permissions:
  issues: write

jobs:
  papers:
    runs-on: ubuntu-latest
    steps:
      - name: Generate papers
        id: paper
        run: |
          sudo gem install nokogiri
          prompt_text="请合并以下文本，输出为markdown格式的表格："
          for i in {1..5};do
            echo $i

            text=$(curl -s "https://arxiv.org/search/cs?query=llm&searchtype=all&abstracts=show&order=-announced_date_first&size=25" | nokogiri -e 'puts $_.at_css("ol.breathe-horizontal li:nth-child('$i')").text' | tr -d '\n')

            echo $text
            
            # res=$(curl -H 'Content-Type: application/json' \
            #            -d '{"contents":[{"parts":[{"text":"aaa"}]}]}' \
            #            -X POST "https://palm-proxy2-kappa.vercel.app/v1beta/models/gemini-pro:generateContent?key=${{ secrets.GEMINI_TOKEN }}" \ 
            #            | jq -r '.candidates[0].content.parts[0].text')

            res="1"
            
            prompt_text+="$res ；"

            sleep 5
          done

          echo $prompt_text
          
          title=`date "+%Y-%m-%d"`
          echo "TITLE=$title" >> "$GITHUB_OUTPUT"

          body=$(curl -H 'Content-Type: application/json' \
                      -d '{"contents":[{"parts":[{"text":"'$prompt_text'"}]}]}' \
                      -X POST "https://palm-proxy2-kappa.vercel.app/v1beta/models/gemini-pro:generateContent?key=${{ secrets.GEMINI_TOKEN }}" \
                      | jq -r '.candidates[0].content.parts[0].text')
          echo $body
      - name: create an issue
        uses: dacbd/create-issue-action@main
        with:
          token: ${{ github.token }}
          title: Papers ${{ steps.paper.outputs.TITLE }}
          body: '  '
          
